ngrok-api:
	ngrok http --domain=formally-closing-possum.ngrok-free.app 5006

ngrok-rasa:
	ngrok http --domain=marlin-upright-adversely.ngrok-free.app 5005

run-api:
	uvicorn voice_modules_fast_api:app --reload --host localhost --port 5006
